name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: windows
            artifact: windowsBuild
            bin_path: export/release/windows/bin

          - os: ubuntu-latest
            target: linux
            artifact: linuxBuild
            bin_path: export/release/linux/bin

          - os: macos-latest
            target: mac
            artifact: macosBuild
            bin_path: export/release/macos/bin

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Install Haxelib (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          haxelib setup C:/haxelib
          haxelib install lime 7.9.0 --quiet
          haxelib install openfl --quiet
          haxelib install flixel 4.11.0 --quiet
          haxelib install flixel-ui --quiet
          haxelib install flixel-addons --quiet
          haxelib install hscript --quiet
          haxelib git polymod https://github.com/larsiusprime/polymod.git --quiet
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc --quiet
          haxelib run lime setup -y
          haxelib list

      - name: Install Haxelib (Linux / macOS)
        if: runner.os != 'Windows'
        run: |
          haxelib setup ~/haxelib
          haxelib install lime 7.9.0 --quiet
          haxelib install openfl --quiet
          haxelib install flixel 4.11.0 --quiet
          haxelib install flixel-ui --quiet
          haxelib install flixel-addons --quiet
          haxelib install hscript --quiet
          haxelib git polymod https://github.com/larsiusprime/polymod.git --quiet
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc --quiet
          haxelib run lime setup -y
          haxelib list

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            libgl1-mesa-dev \
            libglu1-mesa-dev \
            libasound2-dev \
            libx11-dev \
            libxext-dev \
            libxi-dev \
            libxrandr-dev \
            libpulse-dev

      - name: Create APIStuff
        run: echo "package;class APIStuff{public static var API:String = '';public static var EncKey:String = '';}" > source/APIStuff.hx

      - name: Compile
        run: haxelib run lime build ${{ matrix.target }} -release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: ${{ matrix.bin_path }}
